version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./database:/app/database
      - ./videos:/app/videos
      - ./thumbnails:/app/thumbnails
      - ./uploads:/app/uploads
      - ./carousel:/app/carousel
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key-here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # 可选：添加 nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - web
  #   restart: unless-stopped